name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/nintendo-center-registry/game-collection:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to registry with a short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to the registry
        run: docker push registry.digitalocean.com/nintendo-center-registry/game-collection:$(echo $GITHUB_SHA | head -c7)